# Site settings
title: dmelon
shortname: dmelon
email: chend.1991@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  非专业工程师
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dmelon.github.io" # the base hostname & protocol for your site
google_analytics: UA-XXXXXXX-1 #your GA unique id, e.g. UA-xxxxxxxx-x
author: "陈东"  # Yourname
github_username: "dmelon" #
repository: dmelon/dmelon.github.io
disqus_shortname:  #Add Disqus comment to your post
weibo:
  username: dmelon_

logo: /assets/icons/512.png
social:
  name: dmelon
  links:
    - https://weibo.com/u/7038140796
    - https://github.com/dmelon

sass:
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true


plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
    - {scope: { type: posts }, values: { layout: post, comments: true, permalink: '/blog/:title' }}

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

paginate: 10
paginate_path: '/blog/:num/'
